platform :ios do
    desc "Deploy ios YCLIENTS app on the appstore"

    lane :beta_yclients do
      cert # Установка сертификатов
      sigh # Установка provision profiles
      increment_version_number # Увеличение номера версии
      # Зайти в Build Settings/Versioning
      # Выставить Versioning System в Apple Generic и Current Project Version в 1
      gym # Сборка билда 
      upload_to_testflight
      (
           skip_submission: true, # Загрузка будет только ipa файла
           skip_waiting_for_build_processing: true # Не дожидаемся окончания processing
      )
      slack(message: "iOS-сборка готова к бета-тестированию. Ожидает вас в TestFlight")
    end
  
    lane :deploy_yclients do
      match(
        type: "appstore",
        git_url: "https://bitbucket.org/Almouro/certificates" # REPLACE WITH YOUR PRIVATE REPO FOR MATCH
      )
      cordova(platform: 'ios') # Using the Cordova Fastlane Plugin
      appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
    end
  end
  
  platform :android do
    desc "Deploy android YCLIENTS app on play store"
  
    lane :deploy yclients do
      cordova(
        platform: 'android',
        keystore_path: './prod.keystore', # REPLACE THESE LINES WITH YOUR KEYSTORE INFORMATION
        keystore_alias: 'prod',
        keystore_password: 'password'
      ) # Cordova Fastlane Plugin
      supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
    end
  end